version: '3.9'
services:
  python-app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    depends_on:
      - timescaledb
    environment:
      - DB_HOST= timescaledb
      - DB_PORT=5432
      - DB_NAME=weather
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather
    ports:
      - "5432:5432" #[host_port]:[container_port]